#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

#Set map type
map_type: costmap 

#Obstacle marking parameters
obstacle_range: 3 #maximum range sensor reading that will result in an obstacle being put into the costma(meters)
raytrace_range: 8 #range in meters at which to raytrace out obstacles from the map using sensor data. This can be over-ridden on a per-sensor basis.

#The footprint of the robot 
footprint: [ [0.27, 0.23], [0.27, -0.23], [-0.32, -0.23], [-0.32, 0.23] ]

#Cost function parameters
inflation_radius: 0.65

#Configuration for the sensors/topics that the costmap will use to update a map
observation_sources: scan kinect #scan_back

scan: {sensor frame: base_laser, data_type: LaserScan, topic: scan, expected_update_rate: 0.15, marking: true, clearing: true}

#scan_back: {sensor frame: hokuyo_laser, data_type: LaserScan, topic: /hokuyo/scan, expected_update_rate: 0.3, marking: true, clearing: true}


kinect: {sensor frame: camera_link, data_type: PointCloud2, topic:  /voxel_grid_kinect/output , observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.25, max_obstacle_height: 1.5}
