 #Set the acceleration limits of the robot in meters/sec^2  
  acc_lim_x: 0.25
  acc_lim_theta: 0.75 

  #Set the velocity limits of the robot
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.6
  min_vel_theta: -0.6
  min_in_place_vel_theta: 0.5
  escape_vel: -0.1
  holonomic_robot: false
  oscillation_reset_distance: 0.2
